spring:
  config:
    import: D://env/p6e-coat-file-application.yml
  servlet:
    multipart:
      max-request-size: 12MB
      max-file-size: 10MB
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: service-1
          uri: http://127.0.0.1:25400
          predicates:
            - Path=/console/**

logging:
  config: 'classpath:p6e-coat-logback.xml'




