spring:
  config:
    import: D://env/p6e-coat-file-application.yml
  servlet:
    multipart:
      max-request-size: 15MB
      max-file-size: 12MB
logging:
  config: 'classpath:p6e-coat-logback.xml'

p6e:
  coat:
    file:
      downloads:
        test:
          path: 'E://a/'
      resources:
        test:
          path: 'E://a/'
          suffixes:
            jpg: image/jpeg
            png: image/png
            jpeg: image/jpeg
            mp4: video/mp4
      simple-upload:
        path: 'E://a/'
        max-size: 15728640
      slice-upload:
        path: 'E://a/'
        max-size: 15728640
