spring:
  security:
    oauth2:
      client:
        reg
  cloud:
    gateway:
      routes:
        - id: route1
          uri: https://baidu.com
          predicates:
            - Path=/test/**
          filters:
            - AddRequestHeader=X-Custom-Header, CustomValue
  config:
    import: D:\\env\p6e-coat-file-application.yml
logging:
  config: 'classpath:p6e-coat-logback.xml'
